#!/usr/bin/env bash

selected=$(find ~/personal ~/Downloads ~/Documents ~/work -maxdepth 1 -mindepth 1 -type d 2>/dev/null | fzf)

if [[ -z "$selected" ]]; then
    exit 0
fi
selected_name=$(basename "$selected" | tr ".,: " "____")

switch_to() {
    if [[ -z "$TMUX" ]]; then
        tmux attach-session -t "$selected_name"
    else
        tmux switch-client -t "$selected_name"
    fi
    tmux send-keys -t "${selected_name}:0.0" "ready-tmux" Enter
}

if tmux has-session -t "$selected_name" 2>/dev/null; then
    switch_to
else
    tmux new-session -ds "$selected_name" -c "$selected"
    switch_to
fi
